"""empty message

Revision ID: 5c54d3e03a14
Revises: b0ab01246a51
Create Date: 2025-10-31 21:15:15.683468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c54d3e03a14'
down_revision = 'b0ab01246a51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('eye_color', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('hair_color', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_column('hair_color')
        batch_op.drop_column('eye_color')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
